name: Create a release from a tag

# https://github.com/actions/create-release
# https://github.com/actions/upload-release-asset

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: R CMD build .

    - name: Extract package version from tag reference
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Release notes
      run: echo "Release notes for version ${{ env.version }}..." > RELEASE_NOTES
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Version ${{ env.version }}
        body_path: RELEASE_NOTES
        draft: false
        prerelease: false

    - name: Upload package tarball as release asset
      id: upload-release-asset-tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./test_${{ env.version }}.tar.gz
          asset_name: test_${{ env.version }}.tar.gz
          asset_content_type: application/gzip

    - name: Upload a PDF as release asset
      id: upload-release-asset-pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./git-cheat-sheet-education.pdf
          asset_name: Manual for ${{ env.version }}
          asset_content_type: application/pdf
